# Site settings
title: The Longest Journey HD
description: > # this means to ignore newlines until "baseurl:"
  The Longest Journey HD is a game mod which includes
  neural network upscaled backgrounds and sprites,
  redrawn user interface and many other small improvements.
baseurl: ""
url: https://tljhd.github.io

# Build settings
markdown: kramdown

# Google Analytics
google_analytics: UA-140413978-1
